server:
  port: 8080
  forward-headers-strategy: framework


spring:
  session:
    store-type: jdbc

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: com.homihq.manager.core.dialect.PostgresSQL10JsonDialect

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB


  mvc:
      throw-exception-if-no-handler-found: true


logging:
  level:
    org.springframework.security: info
    org.springframework.web: info
    org.springframework.jdbc: info
    org.springframework.session: info
    org.springframework: info
    com.getarjun: info
    net.ttddyy.dsproxy.listener: info
    #org.hibernate.SQL: trace
    #org.hibernate.type.descriptor.sql.BasicBinder: info
    #sql: info
    # org.apache.http: DEBUG
    # httpclient.wire: DEBUG


aws:
  ses:
    awsAccessKey: ${AWS_ACCESS_KEY}
    awsSecretKey: ${AWS_SECRET_KEY}
    region:  ${AWS_REGION}


hash:

