spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVER:arjun-prod.c1c3ax1jvdbz.us-east-1.rds.amazonaws.com}:${DB_PORT:3452}/${DB_NAME:arjundb}
    username: ${DB_USER:arjunk}
    password: ${DB_PASSWORD:Kolkata84}




app:
  signup:
    verify: https://do.homihq.com/verification
