spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}




app:
  signup:
    verify: https://platform.homidev.com/verify


